[build]
  command = "npm install"

[functions]
  node_bundler = "esbundle"

[functions."analyze"]
  timeout = 300

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
